spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scsample?serverTimezone=GMT
    username: root
    password: 123456
server:
  port: 8090
feign:
  hystrix:
    enabled: true
