# 配置输出日志
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
#开启端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
server:
  port: 8070
spring: 
  redis: 
    host: localhost
    port: 6379
  cloud:
    gateway:
      routes:
      - id: userinfo_route
        uri: 
          http://localhost:8081/user/account/userinfo/get
        predicates: 
        - Path=/user/get
        filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
            key-resolver: "#{@ipKeyResolver}"
