# 配置输出日志
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
#开启端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
server:
  port: 8070
cloud: 
    consul:
      host: localhost  
      port: 8500
      discovery:
        enabled: true
        healthCheckPath: /health
        healthCheckInterval: 30s
        ip-address: true
        instance-id: sc-gateway
        hostname: localhost
      enabled: true
