spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scsample?serverTimezone=GMT
    username: root
    password: 123456
server:
  port: 8082
management:
  security:
     enabled: false
feign:
  hystrix:
    enabled: true
mybatis:
  type-aliases-package: com.minstone.sc.sample.domain
  mapper-locations:
  - classpath:mapper/*.xml
