spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scsample?serverTimezone=GMT
    username: root
    password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: minstone
    password: minstone
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
server:
  port: 8081
management:
  security:
     enabled: false
  endpoints: 
   web:
      exposure:
          include: "*"
feign:
  hystrix:
    enabled: true
mybatis:
  type-aliases-package: com.minstone.sc.sample.domain
  mapper-locations:
  - classpath:mapper/*.xml
