spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scsample?serverTimezone=GMT
    username: root
    password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: saas-oa
    password: 123
server:
  port: 8081
feign:
  hystrix:
    enabled: true
mybatis:
  type-aliases-package: com.minstone.sc.sample.domain
  mapper-locations:
  - classpath:mapper/*.xml
